=== SparkleX/db-conn/schema/table.json
{
	"$schema": "https://json-schema.org/draft/2019-09/schema",
	"properties": {
        "$schema": {
            "type": "string"
		},		
        "name": {
			"type": "string",
			"minLength": 1,
  			"maxLength": 20
        },
        "description": {
            "type": "string"
		},
		"columns":{
			"$ref": "#/definitions/columns"
		},
		"primaryKey":{
			"type":"array",
			"items": {
				"type":"string"
			}
		},	
		"uniqueIndexes":{
			"$ref": "#/definitions/indexes"
		},
		"nonUniqueIndexes":{
			"$ref": "#/definitions/indexes"
		}						
	},
	"additionalProperties": true,
    "definitions": {
        "columns":{
			"type": "array",
			"minItems": 1,
			"items": {
				"$ref": "#/definitions/column"
			}
		},
		"column":{
			"type": "object",
			"required": ["name", "type"],
			"properties": {
				"name": "string",
				"type": {
					"type": "string",
					"enum": ["guid","string", "number", "decimal", "datetime"]
				},
				"size": {
					"type": "number"					
				},
				"description": "string",
				"nullable": "boolean"
			},
			"additionalProperties": false
		},
        "indexes":{
			"type": "object",
			"minItems": 1,
			"items": {
				"type":"array",
				"items": {
					"type":"string"
				}
			}
		}				
    }	
}

=== SparkleX/db-conn/test/ddl/tables/Exam.json
{
	"$schema": "../../../schema/table.json",
	"name":"Exam",	
	"description":"Examination",
	"columns": [
		{
			"name":"id",
			"type":"number"
		},
		{
			"name":"code",
			"type":"string",
			"size": 64
		},		
		{
			"name":"name",
			"type":"string",
			"size": 64
		},
		{
			"name":"examDate",
			"type":"datetime"
		}
	],
	"primaryKey": ["id"],
	"uniqueIndexes":{
		"CODE":["code"]
	},
	"nonUniqueIndexes":{
		"NAME":["name"]
	}
}
